CREATE TABLE IF NOT EXISTS magic_links (
    id SERIAL PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    expires TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);